packages:
  - 'frontend'
  - 'server'
  - 'packages/**'



catalog:
  typescript: ^5.8.3
  react: ^19.0.0
  react-dom: ^19.0.0
  zod: ^3.24
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@types/node": ^22